In [2]:
import pandas as pd
import numpy as np
import re

#for sentiment analyzing
import nltk
import random
from nltk.tokenize import word_tokenize

#for basic preprocessing
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.text import Text
import string, re
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/siddhipatel/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/siddhipatel/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/siddhipatel/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [45]:
#HELPER FUNCTIONS

#remove punctuations, numbers, and special characters
def remove_special(df):
    df['Text'] = df['Text'].str.replace("[^\w\d'\s]+", '')
    return df

In [ ]:
def clean_up(text):

In [46]:
biden_url = 'https://raw.githubusercontent.com/srpatel2000/Elections2020/master/Tweets/2020_Elections/Biden_Tweets.csv'
biden_df = pd.read_csv(biden_url, error_bad_lines= False)
biden_df

,timestamp,Username,Retweets,Text,Mentions,Hashtags
0,Thu Apr 25 16:59:59 +0000 2019,980275870655893504,0,"And, we have President Trump to thank.",NaN,NaN
1,Thu Apr 25 16:59:59 +0000 2019,102468365,0,pic.twitter.com/PxypFuZzdb,NaN,NaN
2,Thu Apr 25 16:59:58 +0000 2019,827325184432603136,0,The “hang em high” references were less than s...,NaN,NaN
3,Thu Apr 25 16:59:57 +0000 2019,753734119893393408,0,"Donald Trump Makes Joe Biden’s Point, Mocking ...",NaN,NaN
4,Thu Apr 25 16:59:57 +0000 2019,140074335,0,"Factually speaking, that’s not accurate. Trump...",NaN,NaN
...,...,...,...,...,...,...
52795,Sat Apr 11 11:49:37 +0000 2020,1236376132825612290,0,Yes he have to for some whom haven’t hear it b...,NaN,NaN
52796,Sat Apr 11 11:49:36 +0000 2020,874403447667404800,0,"No, no... this way Joe, this way........... th...",NaN,NaN
52797,Sat Apr 11 11:49:36 +0000 2020,1010964754708303872,0,You want more of this? #TaraReadeBlackoutpic.t...,NaN,#TaraReadeBlackoutpic
52798,Sat Apr 11 11:49:36 +0000 2020,3775550189,0,LA voter- it literally doesn’t matter. You can...,NaN,NaN
52799,Sat Apr 11 11:49:35 +0000 2020,1225504409809047552,0,I think someone from Texas or Florida will be ...,NaN,NaN

In [47]:
biden_df_test = remove_special(biden_df)
biden_df_test

,timestamp,Username,Retweets,Text,Mentions,Hashtags
0,Thu Apr 25 16:59:59 +0000 2019,980275870655893504,0,And we have President Trump to thank,NaN,NaN
1,Thu Apr 25 16:59:59 +0000 2019,102468365,0,pictwittercomPxypFuZzdb,NaN,NaN
2,Thu Apr 25 16:59:58 +0000 2019,827325184432603136,0,The hang em high references were less than subtle,NaN,NaN
3,Thu Apr 25 16:59:57 +0000 2019,753734119893393408,0,Donald Trump Makes Joe Bidens Point Mocking Ca...,NaN,NaN
4,Thu Apr 25 16:59:57 +0000 2019,140074335,0,Factually speaking thats not accurate Trump ha...,NaN,NaN
...,...,...,...,...,...,...
52795,Sat Apr 11 11:49:37 +0000 2020,1236376132825612290,0,Yes he have to for some whom havent hear it be...,NaN,NaN
52796,Sat Apr 11 11:49:36 +0000 2020,874403447667404800,0,No no this way Joe this way that's the kitchen,NaN,NaN
52797,Sat Apr 11 11:49:36 +0000 2020,1010964754708303872,0,You want more of this TaraReadeBlackoutpictwit...,NaN,#TaraReadeBlackoutpic
52798,Sat Apr 11 11:49:36 +0000 2020,3775550189,0,LA voter it literally doesnt matter You can st...,NaN,NaN
52799,Sat Apr 11 11:49:35 +0000 2020,1225504409809047552,0,I think someone from Texas or Florida will be ...,NaN,NaN

In [44]:
string = "warhol's art used many types of media, including hand drawing, painting, photography, silk screening, sculpture, film, music."
print (re.sub("[^\w\d'\s]+",'',string))

warhol's art used many types of media including hand drawing painting photography silk screening sculpture film music